apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-docker
  template:
    metadata:
      labels:
        app: demo-docker
    spec:
      containers:
      - name: demo-docker
        image: localhost:32000/codingsoldier/demo-docker:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - name: http
          containerPort: 16000
---
apiVersion: v1
kind: Service
metadata:
  name: service-demo-docker
spec:
  selector:
    app: demo-docker
# 使用NodePort类型的Service，绑定service的30201端口到宿主机，以便在物理机上调用
  type: NodePort
  ports:
  - name: http
    port: 16000
    targetPort: 16000
#   暴露端口取值范围是30000-32767
    nodePort: 30333





















